### ISSUE TITLE
Upgrade the utilized OLM operator-sdk

### ISSUE THREAD

**Issue by RoddieKieley** [artemiscloud/activemq-artemis-operator#129] opened 2022-01-19 14:55 UTC
**Is your feature request related to a problem? Please describe.**
As time has gone on the base operator-sdk and it would be worthwhile to look at [Upgrade SDK Version](https://sdk.operatorframework.io/docs/upgrading-sdk-version/) so that the base can move to a more recent version in the 1.y line.

**Describe the solution you'd like**
While the latest operator-sdk is currently [v1.16.0](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.16.0/) I think the core requirement here would be to move to something as new as possible in the 1.y line.

**Additional context**
In addition to moving to a newer tool, which has many feature additions, there is an added benefit that many transitive dependencies are upgraded as well.

**Comment by brusdev** [comment] 2023-02-22 09:58
Duplicate of #256

**Closed by brusdev** 2023-02-22 09:58 UTC
Labels: enhancement
