### ISSUE TITLE
Broker not running when persistence is enabled to "true"

### ISSUE THREAD

**Issue by mraslam** [artemiscloud/activemq-artemis-operator#52] opened 2021-02-05 21:53 UTC
**Describe the bug**
I am trying to enable persistence volume for the broker cr. I have set the below values to true as per documentation but the pod does not come up. The pv/pvc creation is successful and also attached to the container but the pod is not responding(stuck in 0/1 Running status)

**persistenceEnabled: true**
**messageMigration: true**

**Platform (please complete the following information):**
 - OS: Running on EKS with custom amazon2 AMI

**Expected behavior**
The persistent volume should be attached and the pod should run normally.

NAME                                         READY                                            STATUS    RESTARTS   AGE
activemq-artemis-operator-6c99865dfb-h967n                                  1/1     Running   0          17h
ex-aao-ss-0                                                                                          0/1     Running   0          17m

Complete Log File Attached
[MQ_Error_Log.txt](https://github.com/artemiscloud/activemq-artemis-operator/files/5935514/MQ_Error_Log.txt)

**Comment by mraslam** [comment] 2021-02-05 21:56
@RoddieKieley @gaohoward

**Comment by gaohoward** [comment] 2021-02-08 03:30
Hi @mraslam Can you share your broker cr file?

**Comment by gaohoward** [comment] 2021-02-08 04:18
@mraslam 
From the log it seems that the persistence store is not correctly set up. Can you log in to the broker pod and check if 
There is any files under this directory: /opt/ex-aao/data/ ?

**Comment by mraslam** [comment] 2021-02-08 13:46
@gaohoward There are no file under the directory /opt/ex-aao/data. Also, it has root permissions and not jboss, i guess that is the reason the broker is unable to create directories under that mount point.

<img width="188" alt="active2" src="https://user-images.githubusercontent.com/72039356/107227993-19bccf00-69ea-11eb-88d5-753732696f72.PNG">

**Comment by gaohoward** [comment] 2021-02-08 14:34
@mraslam I just deployed your cr and it seems fine. 

[jboss@ex-aao-ss-0 ~]$ ls /opt/ex-aao/data -lrt
total 20
drwxr-xr-x 2 jboss root 4096 Feb  8 14:25 log
drwxr-xr-x 2 jboss root 4096 Feb  8 14:25 paging
drwxr-xr-x 2 jboss root 4096 Feb  8 14:25 large-messages
drwxr-xr-x 2 jboss root 4096 Feb  8 14:25 bindings
drwxr-xr-x 2 jboss root 4096 Feb  8 14:25 journal

Perhaps it's your kuber/openshift cluster has some special settings?

**Comment by mraslam** [comment] 2021-02-08 14:40
@gaohoward I am using Amazon EKS, and there are no additional configuration done.

**Comment by mraslam** [comment] 2021-02-08 18:47
@gaohoward 

Just to let you know that we are using Amazon Linux 2 image. 

I can see that the init container runs some scripts to bring the broker. ['-c', '/opt/amq/bin/launch.sh && /opt/amq-broker/script/default.sh']

Creating Broker with args --silent --role admin --name amq-broker --http-host ex-aao-ss-0.ex-aao-hdls-svc.ucm-tools.svc.cluster.local --java-options=-Djava.net.preferIPv4Stack=true --user XXXXX --password XXXXX --allow-anonymous **--data /opt/ex-aao/data** --no-amqp-acceptor --no-hornetq-acceptor --no-mqtt-acceptor --no-stomp-acceptor --no-autotune --clustered --cluster-user XXXXX --cluster-password XXXXX --host ex-aao-ss-0.ex-aao-hdls-svc.ucm-tools.svc.cluster.local --nio at /home/jboss/amq-broker

The data folder is passed as an argument to the above script. Could you let us know where these scripts are stored on git or are they modifiable so that we can change permissions to jboss.

**Comment by gaohoward** [comment] 2021-02-09 04:31
Hi @mraslam 
The related script is here: https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/blob/633620756813b1f59c8bbbfc91802c7c39ad5a02/modules/activemq-artemis-launch/added/launch.sh#L596

I'd suggest you try custom init image to change the permissions. Here is an example https://github.com/artemiscloud/artemiscloud-examples/tree/main/operator/init/jdbc

**Comment by mraslam** [comment] 2021-02-18 04:00
@gaohoward Thank you for your suggestion. I would also like to know if there is anyway to configure the below files before startup. The main goal is to add a guest user/role and give limited access to queue. I would really appreciate any help on this topic. Thanks in advance.

/var/lib/artemis/etc/broker.xml
/var/lib/artemis/etc/artemis-users.properties
/var/lib/artemis/etc/artemis-roles.properties
/var/lib/artemis/etc/login.config

**Comment by gaohoward** [comment] 2021-02-18 05:15
@mraslam You are welcome. Again I recommend you to use custom init image where you have a chance to modify all of the files you mentioned before launching.

**Comment by bjetal** [comment] 2021-04-23 15:00
I am running into the same problem on using the artemis-persistence-deployment.yaml example deployment.  The fix seems to be to change the pod specification to include a value of '0' in the securityContext.fsGroup setting.

This allows the mounted directory to be writable by the members of group 0 (including the jboss user).

**Comment by bjetal** [comment] 2021-04-27 16:39
I don't think this can be fixed in the init container with the current operator.  The problem is a permissions issue on the root directory of the persistent volume, which is not being mounted in the init containers.

Also, because it is a permissions issue, it probably depends on the storage provider involved and their default permissions on their persistence volumes.  For reference, I was using OpenEBS's Jiva as my storage provider when I ran into this issue.

**Comment by mraslam** [comment] 2021-04-27 16:43
I spent a lot of time trying to make it work and ended up using the helm chart instead.

**Comment by bjetal** [comment] 2021-11-18 16:35
My solution is similar to @georgesberscheid but I updated added fsGroup value of 0.  This seems to be a more secure solution because the Artemis process does not run as root.

**Comment by frasmarco** [comment] 2022-07-07 14:13
My solution below, I changes at the CR level:

```
spec:
  deploymentPlan:
    image: placeholder
    journalType: aio
    messageMigration: true
    persistenceEnabled: true
    size: 2
    podSecurityContext:
      fsGroup: 0
      fsGroupChangePolicy: "OnRootMismatch"
```

**Comment by brusdev** [comment] 2023-01-11 12:02
@bjetal @frasmarco I would like to add your solution to the doc (maybe a `Known Issues` page), are you planning to create a PR to update the doc?

**Closed** 2023-02-22 09:53 UTC
Labels: bug
